// =================== CONSTANTS ===================
export const ADMIN_PIN = "1234";
export const STORAGE_KEY = "book-ai-library-v2";
export const PRESET_COLORS = ["#DC2626","#B91C1C","#7F1D1D","#9A3412","#92400E","#B45309","#CA8A04","#D97706","#C2410C","#16A34A","#15803D","#065F46","#0F766E","#0284C7","#0369A1","#1D4ED8","#1E40AF","#4338CA","#7C3AED","#4C1D95","#9333EA","#BE185D","#991B1B","#374151","#1C1917"];
export const MOOD_OPTIONS = ["Hài hước","Buồn","Vui vẻ","Lãng mạn","Xúc động","Hồi hộp","Ám ảnh","Truyền cảm hứng","Khai sáng","Suy nghĩ","Sợ hãi","Phấn khích","Hùng tráng","Sử thi"];

// =================== DEFAULT BOOKS ===================
export const DEFAULT_BOOKS = [
  { id:1, title:"Số Đỏ", author:"Vũ Trọng Phụng", genres:["Hài hước","Châm biếm","Văn học VN"], themes:["Phê phán xã hội","Trào lộng"], mood:"Hài hước", desc:"Tiểu thuyết châm biếm kinh điển về hành trình leo thang xã hội của Xuân Tóc Đỏ trong xã hội thực dân.", pages:304, year:1936, rating:4.5, emoji:"🎭", color:"#DC2626" },
  { id:2, title:"Nỗi Buồn Chiến Tranh", author:"Bảo Ninh", genres:["Văn học VN","Chiến tranh","Tâm lý"], themes:["Chiến tranh","Tình yêu","Ký ức","Chấn thương"], mood:"Buồn", desc:"Tác phẩm đau đớn và tuyệt đẹp về hậu quả tâm lý của chiến tranh qua lời kể người lính Việt Nam.", pages:248, year:1990, rating:4.7, emoji:"💔", color:"#7F1D1D" },
  { id:3, title:"Dế Mèn Phiêu Lưu Ký", author:"Tô Hoài", genres:["Phiêu lưu","Thiếu nhi","Văn học VN"], themes:["Phiêu lưu","Tình bạn","Trưởng thành"], mood:"Vui vẻ", desc:"Hành trình phiêu lưu kỳ thú của chú dế mèn dũng cảm khám phá thế giới.", pages:176, year:1941, rating:4.8, emoji:"🦗", color:"#16A34A" },
  { id:4, title:"Chí Phèo", author:"Nam Cao", genres:["Văn học VN","Hiện thực phê phán"], themes:["Số phận bi kịch","Bất công xã hội"], mood:"Buồn", desc:"Bi kịch của người nông dân bị xã hội bần cùng hóa và hủy hoại nhân phẩm.", pages:88, year:1941, rating:4.6, emoji:"🌾", color:"#78350F" },
  { id:5, title:"Mắt Biếc", author:"Nguyễn Nhật Ánh", genres:["Tình cảm","Văn học VN","Lãng mạn"], themes:["Tình yêu đơn phương","Tuổi thơ","Nuối tiếc"], mood:"Lãng mạn", desc:"Mối tình đơn phương đẹp đẽ và đau buồn của Ngạn với Hà Lan từ thuở ấu thơ.", pages:254, year:1990, rating:4.8, emoji:"💚", color:"#065F46" },
  { id:6, title:"Cho Tôi Xin Một Vé Đi Tuổi Thơ", author:"Nguyễn Nhật Ánh", genres:["Văn học VN","Hồi ký","Hài hước"], themes:["Tuổi thơ","Kỷ niệm"], mood:"Vui vẻ", desc:"Hành trình hài hước và đáng yêu trở về tuổi thơ với những kỷ niệm không thể quên.", pages:208, year:2008, rating:4.7, emoji:"🎠", color:"#D97706" },
  { id:7, title:"Tôi Thấy Hoa Vàng Trên Cỏ Xanh", author:"Nguyễn Nhật Ánh", genres:["Văn học VN","Gia đình","Tình cảm"], themes:["Tình anh em","Gia đình","Tuổi thơ vùng quê"], mood:"Xúc động", desc:"Câu chuyện cảm động về tình anh em và ký ức tuổi thơ ở vùng quê Việt Nam.", pages:280, year:2010, rating:4.7, emoji:"🌻", color:"#CA8A04" },
  { id:8, title:"Tuổi Thơ Dữ Dội", author:"Phùng Quán", genres:["Văn học VN","Lịch sử","Thiếu nhi"], themes:["Chiến tranh","Yêu nước"], mood:"Xúc động", desc:"Câu chuyện hào hùng về những cậu bé trinh sát dũng cảm trong kháng chiến chống Pháp.", pages:360, year:1988, rating:4.7, emoji:"🎖️", color:"#7C3AED" },
  { id:9, title:"Truyện Kiều", author:"Nguyễn Du", genres:["Thơ Nôm","Văn học VN cổ điển","Lãng mạn"], themes:["Số phận người phụ nữ","Tình yêu bi kịch"], mood:"Lãng mạn", desc:"Kiệt tác thơ Nôm 3254 câu kể về cuộc đời đầy bi kịch và tình yêu bất diệt của nàng Kiều.", pages:200, year:1820, rating:4.9, emoji:"🌸", color:"#BE185D" },
  { id:10, title:"1984", author:"George Orwell", genres:["Viễn tưởng","Dystopian","Kinh điển"], themes:["Độc tài toàn trị","Tự do cá nhân"], mood:"Ám ảnh", desc:"Viễn cảnh đáng sợ về chính phủ toàn trị kiểm soát tuyệt đối mọi khía cạnh cuộc sống.", pages:328, year:1949, rating:4.8, emoji:"👁️", color:"#1E3A5F" },
  { id:11, title:"Nhà Giả Kim", author:"Paulo Coelho", genres:["Triết học","Phiêu lưu","Tâm linh"], themes:["Theo đuổi ước mơ","Hành trình tự khám phá"], mood:"Truyền cảm hứng", desc:"Hành trình đầy triết lý của chàng chăn cừu Santiago đi tìm kho báu và ý nghĩa cuộc đời.", pages:208, year:1988, rating:4.6, emoji:"⚗️", color:"#B45309" },
  { id:12, title:"Harry Potter và Hòn Đá Phù Thủy", author:"J.K. Rowling", genres:["Fantasy","Phiêu lưu","Thiếu nhi"], themes:["Tình bạn","Phép thuật","Thiện vs Ác"], mood:"Phấn khích", desc:"Cậu bé Harry khám phá ra mình là phù thủy và bắt đầu hành trình kỳ diệu tại Hogwarts.", pages:320, year:1997, rating:4.9, emoji:"🪄", color:"#7C3AED" },
  { id:13, title:"Chúa Tể Những Chiếc Nhẫn", author:"J.R.R. Tolkien", genres:["Fantasy","Sử thi","Kinh điển"], themes:["Thiện vs Ác","Tình bạn","Sức mạnh ý chí"], mood:"Hùng tráng", desc:"Sử thi fantasy vĩ đại về hành trình của Frodo tiêu diệt chiếc nhẫn quyền năng tối thượng.", pages:1216, year:1954, rating:4.9, emoji:"💍", color:"#4C1D95" },
  { id:14, title:"Cô Gái Mất Tích", author:"Gillian Flynn", genres:["Trinh thám","Tâm lý","Hồi hộp"], themes:["Hôn nhân độc hại","Bí ẩn tội ác"], mood:"Hồi hộp", desc:"Bí ẩn rùng rợn về vụ mất tích người vợ và những sự thật kinh hoàng ẩn sau hôn nhân.", pages:432, year:2012, rating:4.5, emoji:"🔍", color:"#374151" },
  { id:15, title:"Mã Da Vinci", author:"Dan Brown", genres:["Trinh thám","Lịch sử","Hành động"], themes:["Bí ẩn tôn giáo","Âm mưu lịch sử"], mood:"Hồi hộp", desc:"Hành trình giải mã bí ẩn ẩn giấu trong các kiệt tác nghệ thuật thời Phục Hưng.", pages:454, year:2003, rating:4.3, emoji:"🎨", color:"#1C1917" },
  { id:16, title:"Và Rồi Không Còn Ai", author:"Agatha Christie", genres:["Trinh thám","Kinh điển"], themes:["Bí ẩn giết người","Tâm lý tội phạm"], mood:"Hồi hộp", desc:"Mười người lạ mặt bị cô lập trên đảo và lần lượt chết đi — ai là kẻ giết người bí ẩn?", pages:272, year:1939, rating:4.8, emoji:"🏝️", color:"#0C4A6E" },
  { id:17, title:"Dune", author:"Frank Herbert", genres:["Viễn tưởng","Sử thi","Chính trị"], themes:["Quyền lực đế chế","Tài nguyên và chiến tranh"], mood:"Sử thi", desc:"Sử thi viễn tưởng vĩ đại về cuộc chiến giành quyền kiểm soát hành tinh sa mạc Arrakis.", pages:688, year:1965, rating:4.7, emoji:"🏜️", color:"#92400E" },
  { id:18, title:"Người Về Từ Sao Hỏa", author:"Andy Weir", genres:["Viễn tưởng","Sinh tồn","Khoa học"], themes:["Sinh tồn đơn độc","Hài hước trong tuyệt vọng"], mood:"Phấn khích", desc:"Phi hành gia Mark Watney bị bỏ lại một mình trên Sao Hỏa và dùng khoa học để sống sót.", pages:384, year:2011, rating:4.7, emoji:"🚀", color:"#B91C1C" },
  { id:19, title:"Trò Chơi Cuối Cùng", author:"Orson Scott Card", genres:["Viễn tưởng","Chiến tranh","Thiếu niên"], themes:["Thiên tài quân sự","Gánh nặng số phận"], mood:"Hồi hộp", desc:"Thiên tài trẻ Ender được huấn luyện để dẫn đầu cuộc chiến cuối cùng chống người ngoài hành tinh.", pages:352, year:1985, rating:4.8, emoji:"🎮", color:"#1D4ED8" },
  { id:20, title:"Atomic Habits", author:"James Clear", genres:["Phát triển bản thân","Tâm lý học"], themes:["Xây dựng thói quen","Năng suất"], mood:"Truyền cảm hứng", desc:"Hướng dẫn khoa học để xây dựng thói quen tốt và phá vỡ thói quen xấu một cách bền vững.", pages:320, year:2018, rating:4.8, emoji:"⚛️", color:"#0F766E" },
  { id:21, title:"Sapiens: Lược Sử Loài Người", author:"Yuval Noah Harari", genres:["Lịch sử","Phi hư cấu","Khoa học"], themes:["Tiến hóa loài người","Văn minh nhân loại"], mood:"Khai sáng", desc:"Cái nhìn toàn diện về hành trình loài người từ thời đồ đá đến thế giới hiện đại.", pages:464, year:2011, rating:4.7, emoji:"🦴", color:"#1D4ED8" },
  { id:22, title:"Đắc Nhân Tâm", author:"Dale Carnegie", genres:["Phát triển bản thân","Kỹ năng sống"], themes:["Nghệ thuật giao tiếp","Xây dựng quan hệ"], mood:"Truyền cảm hứng", desc:"Nghệ thuật ứng xử và giao tiếp để xây dựng quan hệ tốt đẹp và đạt được thành công.", pages:288, year:1936, rating:4.6, emoji:"🤝", color:"#15803D" },
  { id:23, title:"Nghĩ Giàu Làm Giàu", author:"Napoleon Hill", genres:["Phát triển bản thân","Kinh doanh"], themes:["Tư duy thành công","Quyết tâm"], mood:"Truyền cảm hứng", desc:"Nguyên tắc tư duy thành công đúc kết từ nhiều năm nghiên cứu những người thành đạt nhất.", pages:320, year:1937, rating:4.5, emoji:"💰", color:"#CA8A04" },
  { id:24, title:"Ikigai", author:"Héctor García", genres:["Tâm lý học","Lối sống","Phi hư cấu"], themes:["Tìm mục đích sống","Hạnh phúc bền vững"], mood:"Truyền cảm hứng", desc:"Bí quyết sống hạnh phúc và trường thọ của người Nhật qua việc tìm kiếm lý do để tồn tại.", pages:208, year:2016, rating:4.5, emoji:"🌅", color:"#C2410C" },
  { id:25, title:"Nghệ Thuật Tinh Tế Của Không Quan Tâm", author:"Mark Manson", genres:["Phát triển bản thân","Triết học thực hành"], themes:["Chọn lọc điều quan trọng","Sống thật"], mood:"Suy nghĩ", desc:"Cách tiếp cận ngược đời để sống tốt hơn bằng cách không quan tâm đến những thứ vô nghĩa.", pages:224, year:2016, rating:4.5, emoji:"🤝", color:"#525252" },
  { id:26, title:"Zero to One", author:"Peter Thiel", genres:["Kinh doanh","Khởi nghiệp","Phi hư cấu"], themes:["Đổi mới sáng tạo","Tư duy khởi nghiệp"], mood:"Khai sáng", desc:"Cách xây dựng công ty tạo ra điều hoàn toàn mới — từ không có gì đến thứ gì đó độc đáo.", pages:224, year:2014, rating:4.5, emoji:"💡", color:"#1E40AF" },
  { id:27, title:"Elon Musk: Sứ Mệnh Tương Lai", author:"Ashlee Vance", genres:["Tiểu sử","Kinh doanh","Khoa học"], themes:["Khởi nghiệp táo bạo","Tham vọng vũ trụ"], mood:"Truyền cảm hứng", desc:"Hành trình phi thường của Elon Musk cách mạng hóa xe điện và chinh phục vũ trụ.", pages:400, year:2015, rating:4.5, emoji:"⚡", color:"#0284C7" },
  { id:28, title:"Kiêu Hãnh và Định Kiến", author:"Jane Austen", genres:["Tình cảm","Kinh điển","Lãng mạn"], themes:["Tình yêu vượt định kiến","Giai cấp xã hội"], mood:"Lãng mạn", desc:"Câu chuyện tình yêu kinh điển giữa Elizabeth Bennet và Mr. Darcy đầy kiêu hãnh và định kiến.", pages:432, year:1813, rating:4.7, emoji:"💝", color:"#BE185D" },
  { id:29, title:"Người Đua Diều", author:"Khaled Hosseini", genres:["Tình cảm","Lịch sử","Gia đình"], themes:["Cứu chuộc tội lỗi","Tình bạn và phản bội"], mood:"Xúc động", desc:"Hành trình đầy nước mắt để cứu chuộc tội lỗi trong bối cảnh Afghanistan biến động.", pages:372, year:2003, rating:4.8, emoji:"🪁", color:"#9333EA" },
  { id:30, title:"Lỗi Của Những Vì Sao", author:"John Green", genres:["Tình cảm","Bi kịch","Thiếu niên"], themes:["Tình yêu khi đối mặt cái chết","Sống trọn vẹn"], mood:"Xúc động", desc:"Mối tình đẹp đẽ và bi thương giữa hai bệnh nhân ung thư tuổi teen.", pages:313, year:2012, rating:4.7, emoji:"⭐", color:"#0E7490" },
  { id:31, title:"Chuyện Người Tùy Nữ", author:"Margaret Atwood", genres:["Dystopian","Nữ quyền","Kinh dị"], themes:["Quyền phụ nữ bị tước đoạt","Độc tài tôn giáo"], mood:"Ám ảnh", desc:"Xã hội thần quyền nơi phụ nữ bị tước đoạt mọi quyền và trở thành công cụ sinh sản.", pages:311, year:1985, rating:4.6, emoji:"🔴", color:"#991B1B" },
  { id:32, title:"Những Người Khốn Khổ", author:"Victor Hugo", genres:["Kinh điển","Lịch sử Pháp","Sử thi"], themes:["Công lý và luật pháp","Tình người","Cứu rỗi"], mood:"Xúc động", desc:"Sử thi vĩ đại nhất văn học Pháp về Jean Valjean và đấu tranh vì công lý và nhân quyền.", pages:1232, year:1862, rating:4.8, emoji:"🕯️", color:"#374151" },
  { id:33, title:"Nhật Ký Anne Frank", author:"Anne Frank", genres:["Hồi ký","Lịch sử","Phi hư cấu"], themes:["Sống trong chiến tranh","Hy vọng và đau khổ"], mood:"Xúc động", desc:"Nhật ký chân thực của cô gái Do Thái 13 tuổi ẩn náu trong Thế chiến II.", pages:283, year:1947, rating:4.8, emoji:"✍️", color:"#5B21B6" },
  { id:34, title:"Giết Con Chim Nhại", author:"Harper Lee", genres:["Kinh điển","Xã hội","Pháp đình"], themes:["Phân biệt chủng tộc","Công lý và đạo đức"], mood:"Suy nghĩ", desc:"Câu chuyện về công lý và đạo đức qua vụ kiện oan sai ở miền Nam nước Mỹ.", pages:336, year:1960, rating:4.8, emoji:"🐦", color:"#166534" },
  { id:35, title:"Shining", author:"Stephen King", genres:["Kinh dị","Tâm lý","Siêu nhiên"], themes:["Điên loạn và ma quái","Nghiện ngập và gia đình"], mood:"Sợ hãi", desc:"Người cha từ từ mất lý trí khi gia đình bị kẹt trong khách sạn ma ám suốt mùa đông.", pages:447, year:1977, rating:4.7, emoji:"👻", color:"#1C1917" },
];
